domain_path: C:\Users\rsmalec\Downloads\vitis_vs\spi_test_platform\export\spi_test_platform\sw\standalone_microblaze_0
app_src_dir: D:\ProgramFiles\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
